# from news.models import *
# user1 = User.objects.create(username='User1', first_name='Artem')
# Author.objects.create(authorUser=user1)
# user2 = User.objects.create(username='User2', first_name='Nastya')
# Author.objects.create(authorUser=user2)
# Category.objects.create(name='News')
# Category.objects.create(name='IT')
# Category.objects.create(name='Skillfactory')
# Category.objects.create(name='GIT')
# Post.objects.create(author=Author.objects.get(authorUser=User.objects.get(username='User1')), categoryType='NW', title='Prewiew1', text='Content1')
# Post.objects.create(author=Author.objects.get(authorUser=User.objects.get(username='User1')), categoryType='AR', title='Title1', text='Text1')
# Post.objects.create(author=Author.objects.get(authorUser=User.objects.get(username='User2')), categoryType='NW', title='Prewiew2', text='Content2')
# Post.objects.create(author=Author.objects.get(authorUser=User.objects.get(username='User2')), categoryType='AR', title='Title2', text='Text2')
# p1 = Post.objects.get(pk=1)
# p2 = Post.objects.get(pk=2)
# p3 = Post.objects.get(pk=3)
# p4 = Post.objects.get(pk=4)
# c1 = Category.objects.get(name='News')
# c2 = Category.objects.get(name='IT')
# c3 = Category.objects.get(name='Skillfactory')
# c4 = Category.objects.get(name='GIT')
# p1.postCategory.add(c1)
# p2.postCategory.add(c1, c2, c3, c4)
# p3.postCategory.add(c2, c3,)
# p4.postCategory.add(c4)
# Comment.objects.create(commentUser=User.objects.get(username='User1'), commentPost = Post.objects.get(pk=1), text='comment text1')
# Comment.objects.create(commentUser=User.objects.get(username='User2'), commentPost = Post.objects.get(pk=1), text='comment text2')
# Comment.objects.create(commentUser=User.objects.get(username='User1'), commentPost = Post.objects.get(pk=2), text='comment text1')
# Comment.objects.create(commentUser=User.objects.get(username='User2'), commentPost = Post.objects.get(pk=3), text='comment text1')
# Comment.objects.create(commentUser=User.objects.get(username='User2'), commentPost = Post.objects.get(pk=4), text='comment text1')
# Post.objects.get(pk=1).like()
# Post.objects.get(pk=1).like()
# Post.objects.get(pk=1).like()
# Post.objects.get(pk=1).like()
# Post.objects.get(pk=2).like()
# Post.objects.get(pk=2).like()
# Post.objects.get(pk=2).like()
# Post.objects.get(pk=2).like()
# Post.objects.get(pk=3).like()
# Post.objects.get(pk=3).like()
# Post.objects.get(pk=4).dislike()
# Post.objects.get(pk=2).dislike()
# Post.objects.get(pk=1).dislike()
# Comment.objects.get(pk=1).like()
# Comment.objects.get(pk=1).like()
# Comment.objects.get(pk=1).dislike()
# Comment.objects.get(pk=2).like()
# Comment.objects.get(pk=2).like()
# Comment.objects.get(pk=2).like()
# Comment.objects.get(pk=2).dislike()
# Comment.objects.get(pk=3).like()
# Author.objects.get(authorUser = User.objects.get(username="User1")).update_rating()
# Author.objects.get(authorUser = User.objects.get(username="User2")).update_rating()
# a = Author.objects.get(authorUser = User.objects.get(username="User1"))
# b = Author.objects.get(authorUser = User.objects.get(username="User2"))
# a.ratingAuthor
# b.ratingAuthor
# Author.objects.get(authorUser = User.objects.get(username="User1")).ratingAuthor
# best = Author.objects.all().order_by('-ratingAuthor').values('authorUser', 'ratingAuthor') [0]
# print(best)
